version: '3.9'
services:
  ui:
    build:
      context: ./src/UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    depends_on:
      - be
    restart: unless-stopped
    networks:
      - my-portfolio-net

  be:
    build:
      context: ./src/BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - my-portfolio-net

networks:
  my-portfolio-net:
    driver: bridge
