export interface PortfolioProject {
  title: string;
  category: string;
  year: string;
  description: string;
  impact: string;
  technologies: string[];
  image: string;
  featured?: boolean;
  liveUrl?: string;
  githubUrl?: string;
}

export const projects: PortfolioProject[] = [
  { title: 'CleanTrack', category: 'B2B SaaS', year: '2026', description: 'Separate portals for cleaning managers, workers, and clients, with scheduling, mobile checklists, proof-of-work photos, and service approvals.', impact: 'Independent product · Three role-based portals', technologies: ['.NET 10', 'Angular 19', 'PostgreSQL', 'SignalR', 'Docker'], image: 'assets/images/cleantrack.webp', liveUrl: 'https://cleantrack.adellajil.com' },
  { title: 'Slotafy', category: 'SaaS Platform', year: '2026', description: 'A restaurant SaaS with QR ordering, kitchen displays, live order updates, Stripe billing, and GitOps deployments.', impact: 'Independent product · Live restaurant platform', technologies: ['.NET 10', 'Angular 21', 'PostgreSQL', 'Stripe', 'Kubernetes'], image: 'assets/images/slotafy.webp', liveUrl: 'https://slotafy.com/' },
  { title: 'Homelab Infrastructure', category: 'Platform Engineering', year: '2026', description: 'Proxmox infrastructure managed with Pulumi and Ansible, with application and monitoring stacks deployed through Komodo.', impact: 'Personal infrastructure · Two Proxmox hosts', technologies: ['Proxmox', 'Pulumi', 'Ansible', 'Docker Compose', 'Grafana'], image: 'assets/images/homelab.webp', featured: true },
  { title: 'SnB: Sell & Buy', category: 'Marketplace API', year: '2021', description: 'A location-based marketplace backend with Google Maps integration, push notifications, Redis caching, and container deployment.', impact: 'Freelance backend work · 100K+ downloads and 50K+ monthly transactions', technologies: ['.NET Core', 'MySQL', 'Docker', 'Firebase', 'Google Maps API', 'Redis'], image: 'assets/images/snb.webp', liveUrl: 'https://www.snbapp.com' },
  { title: 'Spur', category: 'Open Source', year: '2026', description: 'A .NET Result<T> library for explicit error handling, fluent pipelines, and ASP.NET Core integration.', impact: 'Open source · Explicit error handling for .NET', technologies: ['.NET', 'C#', 'NuGet'], image: 'assets/images/spur.webp', githubUrl: 'https://github.com/AdelSS04/Spur', liveUrl: 'https://spur.adellajil.com/' },
  { title: 'Podium360', category: 'Enterprise', year: '2020', description: 'Sustainable-finance product development, reporting, document workflows, portfolio optimization, and Azure cost reduction.', impact: 'Team lead at Podyam · Reduced Azure costs by 30%+', technologies: ['.NET 5', 'Angular', 'Cosmos DB', 'RabbitMQ'], image: 'assets/images/podium.webp', liveUrl: 'https://www.podyam.com' },
  { title: 'Cosmigrator', category: 'Open Source', year: '2026', description: 'A framework for versioned Cosmos DB migrations, with bulk operations, retries, and a CLI for deployment pipelines.', impact: 'Open source · Repeatable Cosmos DB schema and data changes', technologies: ['.NET', 'Cosmos DB', 'C#', 'CLI'], image: 'assets/images/cosmigrator.webp', githubUrl: 'https://github.com/AdelSS04/Cosmigrator', liveUrl: 'https://blog.adellajil.com/blog/cosmigrator-cosmos-db-migrations' },
  { title: 'Clean DDD Architecture', category: 'Open Source', year: '2021', description: 'A .NET reference project demonstrating Domain-Driven Design, repositories, and separation between application logic and infrastructure.', impact: 'Reference architecture · Practical DDD boundaries', technologies: ['.NET Core', 'EF Core', 'DDD', 'CQRS'], image: 'assets/images/clean-ddd.svg', githubUrl: 'https://github.com/AdelSS04/CleanDDDArchitecture' },
  { title: 'Terraform Azure Fullstack Starter', category: 'Cloud & DevOps', year: '2025', description: 'A Terraform starter for Azure applications with separate environments, Auth0 authentication, and GitLab CI/CD configuration.', impact: 'Open source · Repeatable Azure application foundation', technologies: ['Terraform', 'Azure', 'Auth0', 'GitLab CI/CD'], image: 'assets/images/terraform-azure-starter.webp', githubUrl: 'https://github.com/AdelSS04/terraform-azure-fullstack-starter', liveUrl: 'https://blog.adellajil.com/blog/azure-terraform-infrastructure-guide' },
  { title: 'My Portfolio', category: 'Open Source', year: '2025', description: 'An Angular server-rendered portfolio with reusable components, an accessible interaction system, and deployment configuration.', impact: 'Personal platform · Designed, built, and maintained', technologies: ['Angular 20', 'Angular SSR', 'TypeScript', 'Cloudflare', 'GitHub Actions'], image: 'assets/images/my-portfolio.webp', githubUrl: 'https://github.com/AdelSS04/my-portfolio', liveUrl: 'https://portfolio.adellajil.com' },
  { title: 'Angular Reactive Forms Showcase', category: 'Open Source', year: '2025', description: 'An Angular reference project covering typed form groups, custom validators, and reusable reactive-form patterns.', impact: 'Reference project · Typed and reusable form patterns', technologies: ['Angular 18', 'TypeScript', 'Reactive Forms'], image: 'assets/images/angular-form.webp', githubUrl: 'https://github.com/AdelSS04/angular-reactive-forms-showcase', liveUrl: 'https://demo-reactive.vercel.app/' }
];

export const services = [
  { title: 'SaaS products', eyebrow: 'From workflow to production', copy: 'I design tenant-aware .NET services and Angular interfaces for scheduling, ordering, billing, reporting, and day-to-day operations.', benefits: ['Define the product and service boundaries', 'Build role-based web experiences', 'Ship real-time workflows with SignalR'], tools: '.NET · Angular · PostgreSQL · Redis', proof: 'Built and operate two independent multi-tenant SaaS products.' },
  { title: 'APIs & integration', eyebrow: 'Clear boundaries between systems', copy: 'I build REST and gRPC services, background jobs, event-driven workflows, and integrations that are easy to trace when something fails.', benefits: ['Design REST and gRPC contracts', 'Connect queues, events, and external systems', 'Add logs, metrics, retries, and failure handling'], tools: 'ASP.NET Core · gRPC · RabbitMQ · Dapper', proof: 'Hands-on across distributed services, public-sector systems, and marketplace backends.' },
  { title: 'Azure delivery', eyebrow: 'Cloud systems the team can run', copy: 'I work from Terraform and Helm through deployment, diagnostics, and production support. The goal is a system the team understands after release.', benefits: ['Define Azure resources as code', 'Build repeatable deployment paths', 'Diagnose live traffic and infrastructure issues'], tools: 'Azure · AKS · Terraform · Helm · Argo CD', proof: 'Reduced Azure costs by more than 30% at Podyam.' },
  { title: 'Connected devices', eyebrow: 'Secure device-to-cloud flows', copy: 'I build onboarding and provisioning paths for industrial devices using IoT Hub, DPS, X.509 certificates, and event-driven Azure services.', benefits: ['Provision new device types', 'Manage certificate-based onboarding', 'Connect device events to cloud workflows'], tools: 'IoT Hub · DPS · X.509 · Azure Functions', proof: 'Maintain provisioning paths used by more than 5,000 devices.' }
];

export const experience = [
  { period: 'Jul 2024 – Present', company: 'Evident Industrial', role: 'Senior Cloud Full-Stack Developer', location: 'Québec, Canada · Hybrid', summary: 'I build and support cloud software that connects industrial devices to EvidentConnect, a multi-tenant SaaS platform.', achievements: ['Work across three AKS microservices and own several device services, Azure Functions, and operational workflows.', 'Maintain provisioning for 5,000+ devices through IoT Hub, DPS, X.509 certificates, and custom allocation policies.', 'Write ADRs, review pull requests, present technical options, debug production issues, and mentor an intern.'], technologies: ['.NET 8–10', 'Angular 18–21', 'AKS', 'Azure IoT', 'gRPC', 'Terraform'] },
  { period: 'Nov 2022 – Jun 2024', company: 'Cofomo · Revenu Québec', role: 'Full-Stack .NET Developer / Analyst Programmer', location: 'Québec, Canada', summary: 'I delivered application and infrastructure changes for large public-sector systems.', achievements: ['Built features with ASP.NET Core, Angular, Dapper, and Azure DevOps.', 'Reviewed changes, joined story analysis and estimation, and supported system, integration, and user-acceptance testing.', 'Reduced code complexity and improved accessibility, documentation, and release support.'], technologies: ['ASP.NET Core', 'Angular', 'Dapper', 'Azure DevOps'] },
  { period: 'Dec 2020 – Aug 2022', company: 'Podyam', role: 'R&D Development Team Lead', location: 'Tunisia', summary: 'I led a seven-developer team working on Podium360, a multi-tenant sustainable-finance platform.', achievements: ['Built reporting, scheduled jobs, document workflows, and a Python portfolio-optimization API.', 'Worked across .NET, Angular, Cosmos DB, Redis, RabbitMQ, Docker, and Azure services.', 'Cut Azure infrastructure costs by more than 30% through right-sizing and Cosmos DB changes.'], technologies: ['.NET', 'Angular', 'Azure', 'Cosmos DB', 'RabbitMQ', 'Python'] },
  { period: 'Earlier', company: 'SnB', role: 'Freelance Backend Developer', location: 'Remote', summary: 'I built backend services for a geo-proximity marketplace with 100K+ downloads and 50K+ monthly transactions.', achievements: ['Added location-based search, push notifications, Google Maps integration, Redis caching, and container deployment.'], technologies: ['.NET', 'MySQL', 'Redis', 'Docker', 'Firebase'] }
];

export const stack = [
  ['Backend & architecture', '.NET 8–10', 'C#', 'ASP.NET Core', 'REST', 'gRPC', 'EF Core', 'Dapper', 'DDD', 'CQRS'],
  ['Frontend', 'Angular 18–21', 'TypeScript', 'RxJS', 'Signals', 'Tailwind CSS', 'Accessibility'],
  ['Cloud & connected systems', 'Azure', 'AKS', 'IoT Hub', 'DPS', 'Azure Functions', 'Cosmos DB', 'Application Insights'],
  ['Delivery & operations', 'Docker', 'Kubernetes', 'Helm', 'Terraform', 'GitLab CI/CD', 'Argo CD', 'GitHub Actions']
] as const;
